-- Create Database 'DataWarehouse'

USE master;

--  CHECKING EXISTANCE OF DATABASE
IF EXISTS(SELECT 1 FROM sys.databases WHERE NAME = 'DataWarehouse')
BEGIN
    ALTER DATABASE DataWarehouse SET MULTI_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE DataWarehouse;
END;
GO

USE MASTER;
-- CREATION OF DATABASE 
CREATE DATABASE DataWarehouse;

USE DataWarehouse;

Go   -- FIRSTLY EXECUTE FIRST COMMAND BEFORE EXECUTING SECOND COMMAND

CREATE SCHEMA bronze;
GO
CREATE SCHEMA silver;
GO
CREATE SCHEMA gold;


